# Generated by Django 5.2.6 on 2025-10-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_device_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceconfighistory',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
