# Generated by Django 5.2.6 on 2025-10-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_device_config', '0002_deviceconfighistory_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupCommandSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('vendor', models.CharField(max_length=100, unique=True)),
                ('command', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
