# Generated by Django 5.2.6 on 2025-10-17 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_device_config', '0003_backupcommandsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecredential',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credentials', to='netbox_device_config.backupcommandsetting'),
        ),
    ]
