# Generated by Django 5.2.6 on 2025-11-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_device_config', '0004_devicecredential_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backupcommandsetting',
            name='command',
        ),
        migrations.AddField(
            model_name='backupcommandsetting',
            name='commands',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
