# Generated by Django 5.2.6 on 2025-11-14 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0215_rackreservation_status'),
        ('netbox_device_config', '0005_remove_backupcommandsetting_command_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceBackupTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='queued', max_length=20)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='netbox_device_config.devicecredential')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_tasks', to='dcim.device')),
            ],
        ),
    ]
