# Generated by Django 5.2.6 on 2025-11-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_device_config', '0006_devicebackuptask'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicebackuptask',
            name='log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
