# Generated by Django 5.2.9 on 2026-02-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_device_config', '0007_devicebackuptask_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('repo_url', models.CharField(max_length=500)),
                ('branch', models.CharField(default='main', max_length=100)),
                ('local_path', models.CharField(default='/opt/netbox/git-configs', max_length=300)),
                ('ssh_key_path', models.CharField(default='/opt/netbox/.ssh/id_rsa', max_length=300)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='devicebackuptask',
            name='git_commit',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
