# Generated by Django 5.2.9 on 2026-02-07 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0225_gfk_indexes'),
        ('netbox_device_config', '0009_delete_deviceconfighistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('schedule_type', models.CharField(max_length=20)),
                ('time_of_day', models.TimeField(blank=True, null=True)),
                ('day_of_week', models.IntegerField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dcim.device')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
