# Generated by Django 5.2.9 on 2026-02-13 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_device_config', '0011_devicecredential_snmp_community_and_more'),
        ('virtualization', '0052_gfk_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecredential',
            name='virtual_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='virtualization.virtualmachine'),
        ),
    ]
