# Generated by Django 5.2.9 on 2026-02-13 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0225_gfk_indexes'),
        ('netbox_device_config', '0012_devicecredential_virtual_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecredential',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dcim.device'),
        ),
        migrations.AlterField(
            model_name='devicecredential',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='netbox_device_config.backupcommandsetting'),
        ),
        migrations.AlterField(
            model_name='devicecredential',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
